<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>fitbit_api_client</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="fitbit-api-client.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\BodyTimeSeries\**" />
    <EmbeddedResource Remove="Interfaces\BodyTimeSeries\**" />
    <None Remove="Interfaces\BodyTimeSeries\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Json" Version="9.0.8" />
  </ItemGroup>

</Project>
